package me.geuxy.pokemon.enums;

import me.geuxy.pokemon.Pokemon;

public enum EnumPokedex {

    BULBASAUR("Bulbasaur", "1"),
    IVYSAUR("Ivysaur", "2"),
    VENUSAUR("Venusaur", "3"),
    CHARMANDER("Charmander", "4"),
    CHARMELEON("Charmeleon", "5"),
    CHARIZARD("Charizard", "6"),
    SQUIRTLE("Squirtle", "7"),
    WARTORTLE("Wartortle", "8"),
    BLASTOISE("Blastoise", "9"),
    CATERPIE("Caterpie", "10"),
    METAPOD("Metapod", "11"),
    BUTTERFREE("Butterfree", "12"),
    WEEDLE("Weedle", "13"),
    KAKUNA("Kakuna", "14"),
    BEEDRILL("Beedrill", "15"),
    PIDGEY("Pidgey", "16"),
    PIDGEOTTO("Pidgeotto", "17"),
    PIDGEOT("Pidgeot", "18"),
    RATTATA("Rattata", "19"),
    RATICATE("Raticate", "20"),
    SPEAROW("Spearow", "21"),
    FEAROW("Fearow", "22"),
    EKANS("Ekans", "23"),
    ARBOK("Arbok", "24"),
    PIKACHU("Pikachu", "25"),
    RAICHU("Raichu", "26"),
    SANDSHREW("Sandshrew", "27"),
    SANDSLASH("Sandslash", "28"),
    NIDORAN("Nidoran", "29"),
    NIDORINA("Nidorina", "30"),
    NIDOQUEEN("Nidoqueen", "31"),
    NIDOKING("Nidoking", "34"),
    CLEFAIRY("Clefairy", "35"),
    CLEFABLE("Clefable", "36"),
    VULPIX("Vulpix", "37"),
    NINETAILS("Ninetails", "38"),
    JIGGLYPUFF("Jigglypuff", "39"),
    WIGGLYTUFF("Wigglytuff", "40"),
    ZUBAT("Zubat", "41"),
    GOLBAT("Golbat", "42"),
    ODDISH("Oddish", "43"),
    GLOOM("Gloom", "44"),
    VILEPLUME("Vileplume", "45"),
    PARAS("Paras", "46"),
    PARASECT("Parasect", "47"),
    VENONAT("Venonat", "48"),
    VENOMOTH("Venomoth", "49"),
    DIGLETT("Diglett", "50"),
    DUGTRIO("Dugtrio", "51"),
    MEOWTH("Meowth", "52"),
    PERSIAN("Persian", "53"),
    PSYDUCK("Psyduck", "54"),
    GOLDUCK("Golduck", "55"),
    MANKEY("Mankey", "56"),
    PRIMEAPE("Primeape", "57"),
    GROWLITHE("Growlithe", "58"),
    ARCANINE("Arcanine", "59"),
    POLIWAG("Poliwag", "60"),
    POLIWHIRL("Poliwhirl", "61"),
    POLIWRATH("Poliwrath", "62"),
    ABRA("Abra", "63"),
    KADABRA("Kadabra", "64"),
    ALAKAZAM("Alakazam", "65"),
    MACHOP("Machop", "66"),
    MACHOKE("Machoke", "67"),
    MACHAMP("Machamp", "68"),
    BELLSPROUT("Bellsprout", "69"),
    WEEPINBELL("Weepinbell", "70"),
    VICTREEBEL("Victreebel", "71"),
    TENTACOOL("Tentacool", "72"),
    TENTACRUEL("Tentacruel", "73"),
    GEODUDE("Geodude", "74"),
    GRAVELER("Graveler", "75"),
    GOLEM("Golem", "76"),
    PONYTA("Ponyta", "77"),
    RAPIDASH("Rapidash", "78"),
    SLOWPOKE("Slowpoke", "79"),
    SLOWBRO("Slowbro", "80"),
    MAGNEMITE("Magnemite", "81"),
    MAGNETON("Magneton", "82"),
    FARFETCHD("Farfetch'd", "83"),
    DODUO("Doduo", "84"),
    DODRIO("Dodrio", "85"),
    SEEL("Seel", "86"),
    DEWDONG("Dewdong", "87"),
    GRIMER("Grimer", "88"),
    MUK("Muk", "89"),
    SHELLDER("Shellder", "90"),
    CLOYSTER("Cloyster", "91"),
    GASTLY("Gastly", "92"),
    HAUNTER("Haunter", "93"),
    GENGAR("Gengar", "94"),
    ONIX("Onix", "95"),
    DROWZEE("Drowzee", "96"),
    HYPNO("Hypno", "97"),
    KRABBY("Krabby", "98"),
    KINGLER("Kingler", "99"),
    VOLTORB("Voltorb", "100"),
    ELECTRODE("Electrode", "101"),
    EXEGGCUTE("Exeggcute", "102"),
    EXEGGUTOR("Exeggutor", "103"),
    CUBONE("Cubone", "104"),
    MAROWAK("Marowak", "105"),
    HITMONLEE("Hitmonlee", "106"),
    HITMONCHAN("Hitmonchan", "107"),
    LICKITUNG("Lickitung", "108"),
    KOFFING("Koffing", "109"),
    WEEZING("Weezing", "110"),
    RHYHORN("Rhyhorn", "111"),
    RHYDON("Rhydon", "112"),
    CHANSEY("Chansey", "113"),
    TANGELA("Tangela", "114"),
    KANGASKHAN("Kangaskhan", "115"),
    HORSEA("Horsea", "116"),
    SEADRA("Seadra", "117"),
    GOLDEEN("Goldeen", "118"),
    SEAKING("Seaking", "119"),
    STARYU("Staryu", "120"),
    STARMIE("Starmie", "121"),
    MRMIME("Mr. Mime", "122"),
    SCYTHER("Scyther", "123"),
    JYNX("Jynx", "124"),
    ELECTRABUZZ("Electrabuzz", "125"),
    MAGMAR("Magmar", "126"),
    PINSIR("Pinsir", "127"),
    TAUROS("Tauros", "128"),
    MAGIKARP("Magikarp", "129"),
    GYARADOS("Gyaradis", "130"),
    LAPRAS("Lapras", "131"),
    DITTO("Ditto", "132"),
    EEVEE("Eevee", "133"),
    VAPOREON("Vaporeon", "134"),
    JOLTEON("Jolteon", "135"),
    FLAREON("Flareon", "136"),
    PORYGON("Porygon", "137"),
    OMANYTE("Omanyte", "138"),
    OMASTER("Omaster", "139"),
    KABUTO("Kabuto", "140"),
    KABUTOPS("Kabutops", "141"),
    AERODACTYL("Aerodactyl", "142"),
    SNORLAX("Snorlax", "143"),
    ARTICUNO("Articuno", "144"),
    ZAPDOS("Zapdos", "145"),
    MOLTRES("Moltres", "146"),
    DRATINI("Dratini", "147"),
    DRAGONAIR("Dragonair", "148"),
    DRAGONITE("Dragonite", "149"),
    MEWTWO("Mewtwo", "150"),
    MEW("Mew", "151"),
    ;

    private final String name, number;

    EnumPokedex(final String name, final String number) {
        this.name = name;
        this.number = number;
    }

    public Pokemon getPokemon() {
        return new Pokemon(name, number);
    }

}
