package me.geuxy.pokemon.enums;

import me.geuxy.pokemon.Pokemon;

public enum EnumPokedex {

    BULBASAUR("Bulbasaur", "001"),
    IVYSAUR("Ivysaur", "002"),
    VENUSAUR("Venusaur", "003"),
    CHARMANDER("Charmander", "004"),
    CHARMELEON("Charmeleon", "005"),
    CHARIZARD("Charizard", "006"),
    SQUIRTLE("Squirtle", "007"),
    WARTORTLE("Wartortle", "008"),
    BLASTOISE("Blastoise", "009"),
    CATERPIE("Caterpie", "010"),
    METAPOD("Metapod", "011"),
    BUTTERFREE("Butterfree", "012"),
    WEEDLE("Weedle", "013"),
    KAKUNA("Kakuna", "014"),
    BEEDRILL("Beedrill", "015"),
    PIDGEY("Pidgey", "016"),
    PIDGEOTTO("Pidgeotto", "017"),
    PIDGEOT("Pidgeot", "018"),
    RATTATA("Rattata", "019"),
    RATICATE("Raticate", "020"),
    SPEAROW("Spearow", "021"),
    FEAROW("Fearow", "022"),
    EKANS("Ekans", "023"),
    ARBOK("Arbok", "024"),
    PIKACHU("Pikachu", "025"),
    RAICHU("Raichu", "026"),
    SANDSHREW("Sandshrew", "027"),
    SANDSLASH("Sandslash", "028"),
    NIDORAN("Nidoran", "029"),
    NIDORINA("Nidorina", "030"),
    NIDOQUEEN("Nidoqueen", "031"),
    NIDOKING("Nidoking", "034"),
    CLEFAIRY("Clefairy", "035"),
    CLEFABLE("Clefable", "036"),
    VULPIX("Vulpix", "037"),
    NINETAILS("Ninetails", "038"),
    JIGGLYPUFF("Jigglypuff", "039"),
    WIGGLYTUFF("Wigglytuff", "040"),
    ZUBAT("Zubat", "041"),
    GOLBAT("Golbat", "042"),
    ODDISH("Oddish", "043"),
    GLOOM("Gloom", "044"),
    VILEPLUME("Vileplume", "045"),
    PARAS("Paras", "046"),
    PARASECT("Parasect", "047"),
    VENONAT("Venonat", "048"),
    VENOMOTH("Venomoth", "049"),
    DIGLETT("Diglett", "050"),
    DUGTRIO("Dugtrio", "051"),
    MEOWTH("Meowth", "052"),
    PERSIAN("Persian", "053"),
    PSYDUCK("Psyduck", "054"),
    GOLDUCK("Golduck", "055"),
    MANKEY("Mankey", "056"),
    PRIMEAPE("Primeape", "057"),
    GROWLITHE("Growlithe", "058"),
    ARCANINE("Arcanine", "059"),
    POLIWAG("Poliwag", "060"),
    POLIWHIRL("Poliwhirl", "061"),
    POLIWRATH("Poliwrath", "062"),
    ABRA("Abra", "063"),
    KADABRA("Kadabra", "064"),
    ALAKAZAM("Alakazam", "065"),
    MACHOP("Machop", "066"),
    MACHOKE("Machoke", "067"),
    MACHAMP("Machamp", "068"),
    BELLSPROUT("Bellsprout", "069"),
    WEEPINBELL("Weepinbell", "070"),
    VICTREEBEL("Victreebel", "071"),
    TENTACOOL("Tentacool", "072"),
    TENTACRUEL("Tentacruel", "073"),
    GEODUDE("Geodude", "074"),
    GRAVELER("Graveler", "075"),
    GOLEM("Golem", "076"),
    PONYTA("Ponyta", "077"),
    RAPIDASH("Rapidash", "078"),
    SLOWPOKE("Slowpoke", "079"),
    SLOWBRO("Slowbro", "080"),
    MAGNEMITE("Magnemite", "081"),
    MAGNETON("Magneton", "082"),
    FARFETCHD("Farfetch'd", "083"),
    DODUO("Doduo", "084"),
    DODRIO("Dodrio", "085"),
    SEEL("Seel", "086"),
    DEWDONG("Dewdong", "087"),
    GRIMER("Grimer", "088"),
    MUK("Muk", "089"),
    SHELLDER("Shellder", "090"),
    CLOYSTER("Cloyster", "091"),
    GASTLY("Gastly", "092"),
    HAUNTER("Haunter", "093"),
    GENGAR("Gengar", "094"),
    ONIX("Onix", "095"),
    DROWZEE("Drowzee", "096"),
    HYPNO("Hypno", "097"),
    KRABBY("Krabby", "098"),
    KINGLER("Kingler", "099"),
    VOLTORB("Voltorb", "100"),
    ELECTRODE("Electrode", "101"),
    EXEGGCUTE("Exeggcute", "102"),
    EXEGGUTOR("Exeggutor", "103"),
    CUBONE("Cubone", "104"),
    MAROWAK("Marowak", "105"),
    HITMONLEE("Hitmonlee", "106"),
    HITMONCHAN("Hitmonchan", "107"),
    LICKITUNG("Lickitung", "108"),
    KOFFING("Koffing", "109"),
    WEEZING("Weezing", "110"),
    RHYHORN("Rhyhorn", "111"),
    RHYDON("Rhydon", "112"),
    CHANSEY("Chansey", "113"),
    TANGELA("Tangela", "114"),
    KANGASKHAN("Kangaskhan", "115"),
    HORSEA("Horsea", "116"),
    SEADRA("Seadra", "117"),
    GOLDEEN("Goldeen", "118"),
    SEAKING("Seaking", "119"),
    STARYU("Staryu", "120"),
    STARMIE("Starmie", "121"),
    MRMIME("Mr. Mime", "122"),
    SCYTHER("Scyther", "123"),
    JYNX("Jynx", "124"),
    ELECTRABUZZ("Electrabuzz", "125"),
    MAGMAR("Magmar", "126"),
    PINSIR("Pinsir", "127"),
    TAUROS("Tauros", "128"),
    MAGIKARP("Magikarp", "129"),
    GYARADOS("Gyaradis", "130"),
    LAPRAS("Lapras", "131"),
    DITTO("Ditto", "132"),
    EEVEE("Eevee", "133"),
    VAPOREON("Vaporeon", "134"),
    JOLTEON("Jolteon", "135"),
    FLAREON("Flareon", "136"),
    PORYGON("Porygon", "137"),
    OMANYTE("Omanyte", "138"),
    OMASTER("Omaster", "139"),
    KABUTO("Kabuto", "140"),
    KABUTOPS("Kabutops", "141"),
    AERODACTYL("Aerodactyl", "142"),
    SNORLAX("Snorlax", "143"),
    ARTICUNO("Articuno", "144"),
    ZAPDOS("Zapdos", "145"),
    MOLTRES("Moltres", "146"),
    DRATINI("Dratini", "147"),
    DRAGONAIR("Dragonair", "148"),
    DRAGONITE("Dragonite", "149"),
    MEWTWO("Mewtwo", "150"),
    MEW("Mew", "151"),
    ;

    private final String name, number;

    EnumPokedex(final String name, final String number) {
        this.name = name;
        this.number = number;
    }

    public Pokemon getPokemon() {
        return new Pokemon(name, number);
    }

}
